### ISSUE TITLE
Poetry install did not work on mac with m1/m2 because the z3-solver version used doesn't have an arm package

### ISSUE THREAD

**Issue by sethsec-bf** [WithSecureLabs/IAMSpy#1]
I don't know much about poetry but the quick fix was to make the following changes to poetry.lock:

Comment out the old version, add the new version:
```
[[package]]
name = "z3-solver"
#version = "4.8.15.0"
version = "4.10.2.0"
description = "an efficient SMT solver library"
category = "main"
optional = false
python-versions = "*"
```

Then add the last line to the z3-solver metadata section:
```
z3-solver = [
...,
    {file = "z3_solver-4.10.2.0-py2.py3-none-macosx_11_0_arm64.whl", hash = "sha256:5686cb33148db4a3dc7bbe3faec0fdb631c86512c69c6c4971c5d805f764c713"},
]
```

**Comment by Skybound1** [comment]
Hey @sethsec-bf, thanks for raising along with the solution :) I've pushed up a new lock file to `arm-z3` branch, do you mind checking it out and making sure it installs on mac?

**Comment by sethsec-bf** [comment]
Worked like a charm!

**Comment by Skybound1** [comment]
Cool that's been merged in
